added sign-up-in form and token distribution through interceptors
knowde-academy/team-4-fe-angular pull request #10
Opened 2021-08-23 11:54 UTC by jakzda

2021-08-23 13:06 UTC, Isterius requested changes
I know some changes are here because of auto-formatting, but I decided to ask you to add missing types etc 🙏

2021-08-23 13:06 UTC, Isterius commented on src/app/models/user.model.ts
> +}
why is this `UserClass` for? 👀

2021-08-23 13:06 UTC, Isterius commented on src/app/products-page/products-page.component.ts
> +  private onInitForm() {
pls add return type

2021-08-23 13:06 UTC, Isterius commented on src/app/products-page/products-page.component.ts
> +  addProduct() {
pls add return type

2021-08-23 13:06 UTC, Isterius commented on src/app/products-page/products-page.component.ts
> +            this.router.navigate(['/products-page']);
`catchError` should be the last operator, because it's fired only in case of error

2021-08-23 13:06 UTC, Isterius commented on src/app/products-page/products.service.ts
> +  deleteProduct(id: number): Observable<HttpResponse<any>> {
it was typed and you changed type to `any` 👀

2021-08-23 13:06 UTC, Isterius commented on src/app/recipes/recipe-form/recipe-form.component.ts
> +  private populateForm() {
return type

2021-08-23 13:06 UTC, Isterius commented on src/app/recipes/recipe-form/recipe-form.component.ts
> +  private onInitForm() {
return type

2021-08-23 13:06 UTC, Isterius commented on src/app/recipes/recipe-form/recipe-form.component.ts
> +  addRecipe() {
return type

2021-08-23 15:45 UTC, jakzda commented on src/app/auth/auth-interceptor.service.ts
> +    var newRequest = req;
I need to declare it before/outside 'if' statement, because I need to return something in all cases

2021-08-23 15:47 UTC, jakzda commented on src/app/auth/auth-error.interceptor.ts
> +        return throwError(error);
in angular documentation it's advised to use "return of([])" but it doesn't work, so I have found "return EMPTY". I hope it does the job

2021-08-23 16:46 UTC, jakzda commented on src/app/auth/refresh-token.interceptor.ts
> +            this.authService.theUser = 'true';
I dont know if I understand it correctly but by line
'this.authService.theUser = 'true';'
I use setter method in BehaviorSubject soo isnt't it what you mean?
Or should I make another method in interceptor to change value to 'true'?

2021-08-23 17:04 UTC, jakzda commented on src/app/auth/refresh-token.interceptor.ts
> +            };
I dont get it :/ tried but failed

2021-09-01 12:14 UTC, Isterius approved these changes

2021-09-01 12:14 UTC, Isterius commented on src/app/auth/store/auth.effects.ts
> +          .pipe(map(() => LoginSuccess()))
aren't you getting `userObject` in response? you might want to save in state (`LoginSuccess` should write this data to state)

2021-09-01 12:14 UTC, Isterius commented on src/app/auth/store/auth.reducer.ts
> +
unnecessary space

2021-09-01 12:14 UTC, Isterius commented on src/app/header/header.component.html
> +            >Logout</a
you are redirecting user in effects, do you need router link here?

2021-09-01 12:14 UTC, Isterius commented on src/app/auth/auth-interceptor.service.ts
> +export class AuthInterceptorService implements HttpInterceptor {
`AuthInterceptor` is enough, don't need to use `Service` here

2021-09-01 12:14 UTC, Isterius commented on src/app/header/header.component.ts
> +    this.authService.logOut();
you can dispatch `logOut` action here

2021-09-01 12:14 UTC, Isterius commented on src/app/products-page/products-page.component.ts
> +      this.products = products;
this should be done with dispatching `getProducts` action, writing it to store and getting it here from store 👀

2021-09-01 12:14 UTC, Isterius commented on src/app/products-page/products-page.component.ts
> +          return this.productsService.getProductById(id);
this should be done by dispatching `getProductDetails` action, saved in store etc

2021-09-01 12:14 UTC, Isterius commented on src/app/products-page/products-page.component.ts
> +        });
this all should happen in effects (`updateProduct` action etc)

2021-09-01 12:14 UTC, Isterius commented on src/app/products-page/products-page.component.ts
> +      .subscribe((products: Product[]) => (this.products = products));
`deleteProduct` action

2021-09-01 12:14 UTC, Isterius commented on src/app/recipes/recipe-form/recipe-form.component.ts
> +          return this.recipeService.getRecipeById(id);
`getRecipeById` action

2021-09-01 12:14 UTC, Isterius commented on src/app/recipes/recipe-form/recipe-form.component.ts
> +        .subscribe(() => this.router.navigate(['/recipe-list']));
`updateRecipe` action

2021-09-01 12:14 UTC, Isterius commented on src/app/recipes/recipe-form/recipe-form.component.ts
> +        .postRecipe(recipe)
`createRecipe` action

2021-09-01 12:50 UTC, jakzda commented on src/app/auth/auth.component.ts
> +  submitForm(isValid: boolean | null, form: any) {
According to console and docs, form property 'valid' is typed to be 'boolean | null'.
![image](https://user-images.githubusercontent.com/64810185/131673092-ff4b59f1-b5dd-4ea9-94e1-c53c5045fe1f.png).
Same case in type of 'form'  which is actually value of form so I changed name of parameter from 'form' to 'formValue.'

2021-09-02 11:28 UTC, merged