Added possibility to add photos to recipes, fixed bug in number input…
knowde-academy/team-4-fe-angular pull request #15
Opened 2021-09-13 14:10 UTC by jakzda

…, improved a bit recipe detail page

2021-09-13 15:53 UTC, k-chary requested changes

2021-09-13 15:53 UTC, k-chary commented on src/app/recipes/recipe-form/recipe-form.component.ts
> +    this.selectedFile = <File>event.target.files[0];
You wouldn't have to cast to the `File` type if you just used proper type instead of the `any` for `event` parameter. Please google for the more appropriate type that would make it possible to get rid of type casting.

2021-09-13 15:53 UTC, k-chary commented on src/app/recipes/recipe-form/recipe-form.component.ts
> +        Validators.pattern('[ążćęóńźA-Za-zd\\s_-]+'),
À-ž character class should do the trick for diacritics :)

2021-09-13 15:53 UTC, k-chary commented on src/app/recipes/recipe-form/recipe-form.component.ts
>          if (!!recipe) {
Since this condition wraps the whole subscription definition please move it to the filter operator (without the explicit conversion to boolean)

2021-09-13 15:53 UTC, k-chary commented on src/app/recipes/recipe-form/recipe-form.component.ts
>              name: recipe.name,
You can use the destructuring within for the parameter to make the code much shorter.
```
subscribe(({ photo_url, name, content, cooking_time, price }) => {
  ...
  return this.recipeForm({
    name,
    content,
    cooking_time,
    price
  })
```

2021-09-13 15:53 UTC, k-chary commented on src/app/recipes/recipe-form/recipe-form.component.ts
> -    if (recipe.price === 0) recipe.price = undefined;
```
const { price, cooking_time, photo } = this.recipeForm.value;
const recipe = {
  ...(price !== 0 && price !== null && { price }),
  ...(cooking_time !== 0 && cooking_time !== null && { cooking_time }),
  ...(this.selectedFile && { photo })
};
```
I would do something like this, but I want you to use it only if you understand what is happening here. Please ask me if you would need further explanation :) 
Regardless of the approach you choose, please extract the data preparation to a separate method.

2021-09-13 15:53 UTC, k-chary commented on src/app/store/products/products.effects.ts
> +            if (error.status === 422)
I know that JS allows omitting the curly braces for statements like if that contains only one instruction, but trust me, for consistency it is always good to use brackets. If you hate those you can then try using the ternary operator

2021-09-13 15:53 UTC, k-chary commented on src/app/store/recipes/recipes.effects.ts
> +        this.recipeService.getRecipes(1, 99999).pipe(
This is not a change request, but a thing to consider later on. You probably don't want to fetch 100k results at once so it would be nice to think of some kind of pagination

2021-09-13 19:27 UTC, jakzda commented on src/app/auth/auth-interceptor.ts
> +  constructor() {}
Ok, after firsts CRs I had to delete loot of whitespaces so now I try to cut back them.  Anyway I understand idea, I will find balance

2021-09-13 19:33 UTC, jakzda commented on src/app/auth/auth-interceptor.ts
> +    const whiteListUrl = new RegExp(
Interceptor adds to header 5 different properties(?), tokens and etc. One of them is 'content-type' and it changes default value that I need to send post request with FormData payloud.

2021-09-13 19:39 UTC, jakzda commented on src/app/recipes/recipe-form/recipe-form.component.html
> +      oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');"
Huber (Tester) told me that 'e' should not be allowed in input value.
I made it with (keydown) instead of (input) as you suggested because with '(input)' when i tried to change only one letter or slice last letter all value disappeared.

2021-09-14 09:07 UTC, k-chary approved these changes

2021-09-14 09:11 UTC, merged