Fe 01 display all recipes and add routing
knowde-academy/team-4-fe-angular pull request #2
Opened 2021-08-14 12:58 UTC by jakzda

Added:
Bootstrap 5.1
Service with http get to get list of recipes and specific recipe
recipe-list component to display list of recipes with paths to component recipe-view
routing module

2021-08-16 05:29 UTC, Isterius commented
@jakzda you probably created this branch from test branch we've created to learn how to create pull-requests :)
Look at commit list, there's our test commit

Let's try to get rid of it together on today's academy 🤔

2021-08-16 05:57 UTC, Isterius requested changes
most of the comments are about code formatting and unnecessary empty lines

2021-08-16 05:57 UTC, Isterius commented on angular.json
> +
unnecessary empty line

2021-08-16 05:57 UTC, Isterius commented on src/app/app-routing.module.ts
> +
unnecessary empty line

2021-08-16 05:57 UTC, Isterius commented on src/app/app-routing.module.ts
> +
unnecessary empty line

2021-08-16 05:57 UTC, Isterius commented on src/app/app-routing.module.ts
> +
unnecessary empty line

2021-08-16 05:57 UTC, Isterius commented on src/app/app.component.ts
> +  title = 'team4-fe-angularsiema';
is it used?

2021-08-16 05:57 UTC, Isterius commented on src/app/header/header.component.html
> +        </a>
wrong formatting

2021-08-16 05:57 UTC, Isterius commented on src/app/header/header.component.html
> +        </a>
opening and closing of one tag should be indented the same

2021-08-16 05:57 UTC, Isterius commented on src/app/header/header.component.ts
> +  }
no need to keep empty methods (`ngOnInit` & `constructor`)

2021-08-16 05:57 UTC, Isterius commented on src/app/models/recipe-response.model.ts
> +
too many empty lines

2021-08-16 05:57 UTC, Isterius commented on src/app/models/recipe.model.ts
> +    // }
not needed probably

2021-08-16 05:57 UTC, Isterius commented on src/app/recipes/recipe-list/recipe-list.component.html
> +
not needed empty line

2021-08-16 05:57 UTC, Isterius commented on src/app/recipes/recipe-list/recipe-list.component.html
> +  <h1 style="text-align: center;">All recipes</h1>
pls do not use inline styling

2021-08-16 05:57 UTC, Isterius commented on src/app/recipes/recipe-list/recipe-list.component.ts
> +
not needed empty lines

2021-08-16 05:57 UTC, Isterius commented on src/app/recipes/recipe-view/recipe-view.component.ts
> +  recipe: {id:string, name: string, content: string} ={id:'0',name:'0',content:'0'};
pls put more attention to code formatting

also - this approach is good enough for now, but let's discuss other possibilities on Academy :)

2021-08-16 05:57 UTC, Isterius commented on src/app/recipes/recipe-view/recipe-view.component.ts
> +
too many empty lines

2021-08-16 05:57 UTC, Isterius commented on src/app/recipes/recipe.service.ts
> +
not needed empty lines

2021-08-16 05:57 UTC, Isterius commented on src/app/recipes/recipe.service.ts
> +
empty lines :D

2021-08-16 07:01 UTC, Isterius commented on src/app/models/recipe-response.model.ts
> +}
is that full response?

2021-08-16 07:04 UTC, PatrykTyszka commented on src/app/recipes/recipe-view/recipe-view.component.ts
> +}
and one exception :D you should add empty line at the end of file :D

2021-08-17 07:19 UTC, Isterius approved these changes

2021-08-17 07:19 UTC, merged