fixed data allocation, crud products
knowde-academy/team-4-fe-angular pull request #8
Opened 2021-08-20 09:44 UTC by jakzda

2021-08-20 11:01 UTC, Isterius requested changes

2021-08-20 11:01 UTC, Isterius commented on src/app/recipes/recipe-list/recipe-list.component.ts
> +import { Component, OnDestroy, OnInit } from '@angular/core';
not used?

2021-08-20 11:01 UTC, Isterius commented on src/app/recipes/recipe-list/recipe-list.component.ts
> +        console.log(recipes);
`console.log`

2021-08-20 11:07 UTC, jakzda commented on src/app/products-page/products-page.component.ts
> +        this.router.navigate(['/products-page']);
In this case, if its in "edition mode" url is equal to "/products-page/:id". Existence of id parameter defines if form is adding or editing

2021-08-21 16:41 UTC, Isterius approved these changes

2021-08-21 17:17 UTC, merged